sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 990530
  alioss:
    endpoint: oss-us-east-1.aliyuncs.com
    access-key-id: LTAI5tJWRTuBEsPa9dnAh9Cp
    access-key-secret: 5q190f391a58uTxWUUOx4In36LpPzp
    bucket-name: sky-eats
